### ISSUE TITLE
org.sidiff.serge could not be found

### ISSUE THREAD

**Issue by jabiercoding** [mde-optimiser/mde_optimiser#43]
I am having problems with the installation. The update site seems not able to find the plugin org.sidiff.serge. I tried to install this tool from the zip at http://pi.informatik.uni-siegen.de/mrindt/SERGe.php but still this plugin is not there.
`Cannot complete the install because one or more required items could not be found.
  Software being installed: MDEOptimiser 1.0.0.201806200557 (uk.ac.kcl.mdeoptimise.feature.feature.group 1.0.0.201806200557)
  Missing requirement: MDEOptimiser 1.0.0.201806200557 (uk.ac.kcl.mdeoptimise.feature.feature.group 1.0.0.201806200557) requires 'org.sidiff.serge 0.0.0' but it could not be found`

**Comment by alxbrd** [comment]
Installing it from the zip will not work. 

Could you please let me know what version of Eclipse you are using and what is your os?

**Comment by jabiercoding** [comment]
Eclipse Modeling Tools
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200

Windows 10 Pro

Thanks!

**Comment by alxbrd** [comment]
A new version has been published to master that should resolve this issue. We recommend using Eclipse Photon for DSL developers with the latest version of the tool. There is a known bug in Eclipse Oxygen that affects our configuration launcher.

**Comment by jabiercoding** [comment]
I tried with Photon for DSL developers and the current master update site, the installation had no problems, and I managed to run one of your examples. Thanks.
