### ISSUE TITLE
maven compile issue

### ISSUE THREAD

**Issue by isaac-muhumuza** [mde-optimiser/mde_optimiser#47]
Hi Alex,

When I run 'mvn clean compile' on the src folder after cloning the repository onto my local machine - I get an artifact not found. Please see the attached file..
[mvn-clean-compile-error.txt](https://github.com/mde-optimiser/mde_optimiser/files/2619654/mvn-clean-compile-error.txt)
 
Many thanks,
Isaac

**Comment by alxbrd** [comment]
Hi Isaac,

There was a problem with the version of the missing dependency so I updated it to a new version in my p2 repo.

I will update the master branch with a new version that fixes this issue and your problem should be resolved. Before then, you can use this commit that has a working version of the code: 3f103ec9f1d342fec3d22ce37a68d30fe03dc211

Thanks.

**Comment by isaac-muhumuza** [comment]
Hi Alex,

Thanks for getting back. I have tried that commit but its also giving me errors. This time it finds the artifact but there's an error while fetching it. Please see attached file.


Regards,

Isaac

________________________________

**Comment by alxbrd** [comment]
That commit works on the build server without issues. Try again on a different connection perhaps?

**Comment by isaac-muhumuza** [comment]
Hi Alex,

I tried it at home and all is fine. It must have been the connection at KCL.

Are you available at university to have a discussion about the code.

Many thanks.
Isaac.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by alxbrd** [comment]
Glad it worked. Please send me an email to arrange a meeting.

I will close this issue now.
