### ISSUE TITLE
https://mde-optimiser.github.io/

### ISSUE THREAD

**Issue by Gabcddrc** [mde-optimiser/mde_optimiser#53]
On the https://mde-optimiser.github.io/ getting started section, both eclipse update sites links are dead.
![image](https://user-images.githubusercontent.com/36075806/66738288-fde10180-ee65-11e9-98df-a0aecb42c6d5.png)

**Comment by alxbrd** [comment]
The composite site location has changed. I will update the site with the new url shortly.

Thanks for reporting.

**Comment by alxbrd** [comment]
The website has been updated with the latest links for the P2 website. Please try using the "Develop" website following the instructions from the website. That should work just fine.
