### ISSUE TITLE
Error with evolver parameters

### ISSUE THREAD

**Issue by jmhorcas** [mde-optimiser/mde_optimiser#54]
I am trying to pass a parameter to an Henshin rule by specifying it in the .mopt file. 
I am using the default "Random" function that takes a regular expression as a String and return a random value instance of that expression. Here is my specification:
`mutate using <FQAsEvolvers.henshin> unit "changeConfiguration" parameters {delta => Random("1")}`
And my Henshin rule:
![image](https://user-images.githubusercontent.com/5119294/68077472-83e4ce00-fdbc-11e9-8f4e-3b8f3e86ce58.png)

But I always get the following error independently from the regular expression:
![image](https://user-images.githubusercontent.com/5119294/68077502-f2c22700-fdbc-11e9-87b2-dc9dffb248eb.png)

**Comment by alxbrd** [comment]
Thanks for creating this issue so quickly. I was wondering if it would be possible to also send by email a metamodel, a model instance and a henshin file with this operator.

**Comment by alxbrd** [comment]
It turns out that the bug was easy to fix. No need to send me your particular inputs, thanks. A new dev build has been pushed. Please update your version of the tool using the dev p2 install url on the website.

**Comment by jmhorcas** [comment]
Now it's working. Thank you for solving it so fast.
